input_script:
  class: File
  path: /path/to/file
tablemaker_output:
  - {class: Directory, path: /path/to/directory}
  - {class: Directory, path: /path/to/directory}
metadata:
  class: File
  path: /path/to/file
condition: "stringbal"
