threads: 2
salmon_index:
  class: Directory
  path: ../../tests/transcript_index
subject_name1: test1
subject_name2: test2
subject_name3: test3
subject_name4: test4
fastq1:
  - {class: File, path: ../../tests/test1.1.fastq}
  - {class: File, path: ../../tests/test1.2.fastq}
fastq2:
  - {class: File, path: ../../tests/test2.1.fastq}
  - {class: File, path: ../../tests/test2.2.fastq}
fastq3:
  - {class: File, path: ../../tests/test3.fastq}
fastq4:
  - {class: File, path: ../../tests/test4.fastq}
annotation:
  class: File
  path: ../../tests/test.gtf
salmon_count_script:
  class: File
  path: ../../scripts/salmon_R_script.R
DESeq2_script:
  class: File
  path: ../../scripts/Basic_DESeq2.R
metadata:
  class: File
  path: ../../tests/metadata.csv
